# Generated by Django 4.1.9 on 2023-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobileno', models.CharField(max_length=1000)),
                ('inquery', models.CharField(max_length=1000)),
                ('msg', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobileno', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('msg', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
    ]
