# Generated by Django 4.1.9 on 2024-09-08 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_team_rename_text_slider_text_data1_slider_text_data2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASSETS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yearly_income', models.IntegerField(default=0)),
                ('expence_daily', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=100)),
                ('difference_amount', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BATCH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BATCH_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_date', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('COURSE_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('COURSE_fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FEEPAID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('of_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LMSUSER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('BATCH_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('COURSE_duration', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('father_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('material_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('dob', models.CharField(blank=True, max_length=1000, null=True)),
                ('religion', models.CharField(blank=True, max_length=1000, null=True)),
                ('village', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('pincode', models.CharField(blank=True, max_length=1000, null=True)),
                ('district', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('qualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_images')),
                ('student_sign', models.ImageField(blank=True, null=True, upload_to='student_signature')),
                ('student_document', models.ImageField(blank=True, null=True, upload_to='student_document')),
                ('BATCH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.batch')),
                ('COURSE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENTLEDGER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='front_two_images',
        ),
        migrations.DeleteModel(
            name='inquery',
        ),
        migrations.DeleteModel(
            name='newsletter_sub',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='slider_images',
        ),
        migrations.DeleteModel(
            name='slider_text',
        ),
        migrations.DeleteModel(
            name='take_a_tour',
        ),
        migrations.DeleteModel(
            name='team',
        ),
        migrations.AddField(
            model_name='feepaid',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.student'),
        ),
        migrations.AddField(
            model_name='batch',
            name='COURSE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course'),
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.lmsuser'),
        ),
    ]
