# Generated by Django 4.1.9 on 2024-09-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_staff_staffattandance_remove_student_batch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='difference_amount',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='yearly_income',
        ),
        migrations.RemoveField(
            model_name='feepaid',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='feepaid',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='studentledger',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='lmsuser',
            name='yearly_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='BATCH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='COURSE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active_student',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passout_student',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentledger',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
