# Generated by Django 4.1.9 on 2024-09-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='mobile_no',
            new_name='mobileno',
        ),
    ]
