# Generated by Django 4.1.9 on 2024-09-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_mobile_no_login_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
